version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: kleopatra_db
    environment:
      POSTGRES_DB: kleopatra
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
